### ISSUE TITLE
Simpy demo code error

### ISSUE THREAD

**Issue by jinfagang** [IntelVCL/Open3D#838]
Runs this code for demo:

```
points = np.random.rand(10000, 3)
point_cloud = open3d.PointCloud()
point_cloud.points = open3d.Vector3dVector(points)
open3d.draw_geometries([point_cloud])
```

Error:

```
Traceback (most recent call last):
  File "show_pc.py", line 3, in <module>
    from open3d import *
  File "/usr/local/lib/python3.6/dist-packages/open3d/__init__.py", line 34, in <module>
    from open3d.j_visualizer import *
  File "/usr/local/lib/python3.6/dist-packages/open3d/j_visualizer.py", line 27, in <module>
    import ipywidgets as widgets
  File "/usr/local/lib/python3.6/dist-packages/ipywidgets/__init__.py", line 23, in <module>
    from IPython import get_ipython
  File "/usr/local/lib/python3.6/dist-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/embed.py", line 17, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/interactiveshell.py", line 14, in <module>
    from prompt_toolkit.enums import DEFAULT_BUFFER, EditingMode
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/__init__.py", line 2, in <module>
    from .application import Application
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/application.py", line 3, in <module>
    from prompt_toolkit.buffer import Buffer
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/buffer.py", line 9, in <module>
    from .completion import Completer, Completion, CompleteEvent
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/completion/__init__.py", line 2, in <module>
    from .base import Completion, Completer, ThreadedCompleter, DummyCompleter, DynamicCompleter, CompleteEvent, merge_completers, get_common_complete_suffix
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/completion/base.py", line 4, in <module>
    from prompt_toolkit.eventloop import generator_to_async_generator, AsyncGeneratorItem
ImportError: cannot import name 'generator_to_async_generator'

```

BTW, I wanna using open3d to show kitti lidar points, but kitti lidar points are not 3 channel, how to show that?

**Comment by yxlao** [comment]
That works fine for me. How did you install open3d? What python environment do you use to execute the scripts?

![image](https://user-images.githubusercontent.com/1501945/53074836-9cb48a00-34a0-11e9-9431-e2f40c78c236.png)

**Comment by jinfagang** [comment]
@yxlao Turns out to be IPython bad. that package relies on promt-toolkit which is not compatible with higher version python. Just uninstall it and reinstall the newest version IPython solves the problem. Thanks for your reply.
